spring.application.name=College Ride Share

# H2 Database
spring.datasource.url=jdbc:h2:mem:ridesharedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# Thymeleaf
spring.thymeleaf.cache=false

# Server
server.port=${PORT:8080}

# Session
server.servlet.session.timeout=30m
